server:
  port: 8080

spring:
  application:
    name: career-coach-api
#  redis:
#    host: localhost
#    port: 6379
#    timeout: 2000ms

# Rate Limiting 설정
resilience4j:
  ratelimiter:
    instances:
      interview-questions:
        limit-for-period: 5        # 기간당 5번 요청
        limit-refresh-period: 1m   # 1분마다 리셋
        timeout-duration: 0s       # 제한 시 즉시 실패



  # H2 Database ??
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  # JPA ??
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 Console ?? (???)
  h2:
    console:
      enabled: true
      path: /h2-console

# OpenAI API ??
openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key-here}
    base-url: https://api.openai.com/v1
    model: gpt-3.5-turbo
    max-tokens: 1500
    temperature: 0.7

# ?? ??
logging:
  level:
    com.careercoach: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"