# application.yml - 핵심 설정만 남긴 버전
server:
  port: 8080
  shutdown: graceful  # SSE 연결을 위한 우아한 종료

spring:
  application:
    name: career-coach-api

  # JSON 설정
  jackson:
    serialization:
      write-dates-as-timestamps: false  # ISO 8601 날짜 형식 사용
    deserialization:
      fail-on-unknown-properties: false  # 알 수 없는 속성 무시

  # Task 스케줄링 설정 (세션 정리용)
  task:
    scheduling:
      pool:
        size: 2

# OpenAI 설정
openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key-here}
    model: gpt-4o-mini
    temperature: 0.7
    max-tokens: 3000
    timeout: 30s

# 로깅 설정
logging:
  level:
    com.careercoach.careercoachapi: INFO
    org.springframework.web.reactive: WARN
    org.springframework.scheduling: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 관리 및 모니터링
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized