server:
  port: 8080
  tomcat:
    connection-timeout: 10000  # 20초 (기본값)
spring:
  application:
    name: career-coach-api  # 애플리케이션 이름 추가
  datasource:    # HikariCP 커넥션 풀 타임아웃 (가장 중요)
    hikari:
      connection-timeout: 30000     # 30초
      maximum-pool-size: 20         # 최대 커넥션 수
      minimum-idle: 5               # 최소 유휴 커넥션
    url: jdbc:h2:mem:testdb  # H2 설정 명시적 추가
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  # 개발용 DDL 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key-here}
    base-url: https://api.openai.com/v1
    model: gpt-3.5-turbo
    max-tokens: 1500
    temperature: 0.7

logging:
  level:
    com.careercoach.careercoachapi: DEBUG  # 전체 패키지명
    org.springframework.web: DEBUG